### ISSUE TITLE
Feedback Sessions - Tips

### ISSUE THREAD

**Issue by pieteroyens** [lucasfijen/How-far-should-we-step-Policy-Improvement-with-Trust-Region-Optimisation#3]
Feedback Puck
- [ ] Graphs: vergeet niet te zeggen wat je variantie is
- [ ] Introductie te formeel: het is een blog
- [ ] REINFORCE is het probleem, oplossing is NPG en TRPO, welke van de twee is beter <- probleem beter aanduiden in Introductie
- [ ] Let op taalfouten (Pieter!!)
- [ ] Vertel beter waarom NPG en TRPO belangrijk zijn voor RL onderzoek

Feedback Gerson
- [ ] Experimental question nog niet heel duidelijk, en ook niet duidelijk hoe we deze connecten aan onze metrics
- [ ] Meer design elementen (zoals GIFs) zouden voor een blog nice zijn
- [ ] Wat vergelijken we nou? (PPO moet waarschijnlijk weg uit de introductie)
- [ ] Wat is onze hypothese en verwachting?
- [ ] Geen formele descriptions (formules missen)
- [ ] _Hoe_ REINFORCE werkt is nog onduidelijk
- [ ] REINFORCE in introductie moet ff wat duidelijker
- [ ] Baseline is niet duidelijk (hebben we er een? Misschien vanilla gradient descent gebruiken)

**Comment by GuidoVisser** [comment]
[feedback_form_Guido.pdf](https://github.com/lucasfijen/ReinforcementLearning/files/5415844/feedback_form_Guido.pdf)

**Comment by JMitnik** [comment]
[feedback_jonathan.pdf](https://github.com/lucasfijen/ReinforcementLearning/files/5415846/feedback_jonathan.pdf)

**Comment by pieteroyens** [comment]
[Puck_feedback.pdf](https://github.com/lucasfijen/ReinforcementLearning/files/5415849/Puck_feedback.pdf)

**Comment by lucasfijen** [comment]
[Feedback_form-kylian.pdf](https://github.com/lucasfijen/ReinforcementLearning/files/5415930/Feedback_form-kylian.pdf)
